#!/bin/bash
cd /tmp/rom 

. build/envsetup.sh
export SELINUX_IGNORE_NEVERALLOWS=true
lunch nitrogen_platina-userdebug
export SKIP_API_CHECK=true
export SKIP_ABI_CHECK=true
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 50G 
ccache -o compression=true 
ccache -z 

make sepolicy
make bootimage
make init
