#!/bin/bash

mkdir -p /tmp/rom
cd /tmp/rom

repo init --no-repo-verify --depth=1 -u https://github.com/CAF-Extended/manifest -b 11.0 -g default,-device,-mips,-darwin,-notdefault
#git clone https://github.com/D4rkKnight21/local_manifest.git -b cafex --depth=1 .repo/local_manifests
git config --global user.name "D4rkKnight21"
git config --global user.email "yusuff8621@gmail.com"
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

git clone https://github.com/D4rkknight21/device_xiaomi_platina.git -b cafex --depth=1 device/xiaomi/platina
git clone https://github.com/D4rkknight21/device_xiaomi_sdm660-common.git -b aosp --depth=1 device/xiaomi/sdm660-common
git clone https://github.com/D4rkknight21/UghTea.git -b eas --depth=1 kernel/xiaomi/sdm660
git clone https://github.com/D4rkknight21/vendor_xiaomi_platina.git -b 11 --depth=1 vendor/xiaomi/platina
git clone https://github.com/D4rkknight21/vendor_xiaomi_sdm660-common.git -b 11 --depth=1 vendor/xiaomi/sdm660-common
