#!/bin/bash
sudo apt install wget
MANIFEST=https://github.com/Project-Fluid/manifest.git
BRANCH=fluid-11

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice.Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git clone https://github.com/Kota-Gaplek-Project/android_.repo_local_manifest.git -b fluid --depth=1 .repo/local_manifest
git config --global user.name "D4rkKnight21"
git config --global user.email "yusuff8621@gmail.com"

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
